config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :merchants
  resources :landlords
  resources :shops
  resources :products

  get 'qr_codes/forward/:code', to: 'qr_codes#forward', as: :forward

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end

  post "/graphql", to: "graphql#execute"
end

app/models/shop.rb
# == Schema Information
#
# Table name: shops
#
#  id          :integer          not null, primary key
#  name        :string
#  landlord_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  latitude    :float
#  longitude   :float
#  address     :string
#

class Shop < ApplicationRecord
  belongs_to :landlord
  has_many :qr_codes, dependent: :destroy

  validates :name, presence: true
  validates :landlord, presence: true

  geocoded_by :full_street_address   # can also be an IP address
  after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }

  def full_street_address
    address
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  # GET /shops
  # GET /shops.json
  def index
    @shops = Shop.all
    @shops = @shops.where(landlord_id: params[:landlord_id]) if params[:landlord_id].present?
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
  end

  # GET /shops/new
  def new
    @shop = Shop.new
    @landlords = Landlord.all.pluck(:name, :id)
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(shop_params)
    @landlords = Landlord.all.pluck(:name, :id)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_params
      params.require(:shop).permit(:name, :landlord_id)
    end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_form.html.slim
= bootstrap_form_for @shop do |f|
  = f.text_field :name
  = f.select :landlord_id, @landlords

  = f.submit "Submit", class: 'btn btn-default'

app/views/shops/edit.html.slim
h1 Editing shop

== render 'form'

=> link_to 'Show', @shop
'|
=< link_to 'Back', shops_path

app/views/shops/index.html.slim
h3 Listing shops

table.table.table-striped
  thead.thead-default
    tr
      th Name
      th Landlord
      th

  tbody
    - @shops.each do |shop|
      tr
        td = link_to shop.name, shop_path(shop)
        td = link_to shop.landlord.name, landlord_path(shop.landlord)
        td
          = link_to 'Edit', edit_shop_path(shop), class: 'btn btn-primary'
          = link_to 'Destroy', shop, class: 'btn btn-danger', data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Shop', new_shop_path, class: 'btn btn-default'

app/views/shops/new.html.slim
h1 New shop

== render 'form'

= link_to 'Back', shops_path

app/views/shops/show.html.slim
p#notice = notice

p
  strong Name:
  = @shop.name
p
  strong Landlord:
  = link_to @shop.landlord.name, landlord_path(@shop.landlord)

p
  strong Address:
  = "#{@shop.address} (#{@shop.latitude}, #{@shop.longitude})"

p
  = image_tag google_map(center: @shop.address)

=> link_to 'Edit', edit_shop_path(@shop)
'|
=< link_to 'Back', shops_path