config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :merchants
  resources :landlords
  resources :shops
  resources :products

  get 'qr_codes/forward/:code', to: 'qr_codes#forward', as: :forward

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end

  post "/graphql", to: "graphql#execute"
end

app/models/merchant.rb
# == Schema Information
#
# Table name: merchants
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Merchant < ApplicationRecord
  has_many :products, dependent: :destroy

  validates :name, presence: true
end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController
  before_action :set_merchant, only: [:show, :edit, :update, :destroy]

  # GET /merchants
  # GET /merchants.json
  def index
    @merchants = Merchant.all
  end

  # GET /merchants/1
  # GET /merchants/1.json
  def show
  end

  # GET /merchants/new
  def new
    @merchant = Merchant.new
  end

  # GET /merchants/1/edit
  def edit
  end

  # POST /merchants
  # POST /merchants.json
  def create
    @merchant = Merchant.new(merchant_params)

    respond_to do |format|
      if @merchant.save
        format.html { redirect_to @merchant, notice: 'Merchant was successfully created.' }
        format.json { render :show, status: :created, location: @merchant }
      else
        format.html { render :new }
        format.json { render json: @merchant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /merchants/1
  # PATCH/PUT /merchants/1.json
  def update
    respond_to do |format|
      if @merchant.update(merchant_params)
        format.html { redirect_to @merchant, notice: 'Merchant was successfully updated.' }
        format.json { render :show, status: :ok, location: @merchant }
      else
        format.html { render :edit }
        format.json { render json: @merchant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /merchants/1
  # DELETE /merchants/1.json
  def destroy
    @merchant.destroy
    respond_to do |format|
      format.html { redirect_to merchants_url, notice: 'Merchant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_merchant
      @merchant = Merchant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def merchant_params
      params.require(:merchant).permit(:name)
    end
end

app/helpers/merchants_helper.rb
module MerchantsHelper
end

app/views/merchants/_form.html.slim
= bootstrap_form_for @merchant do |f|
  = f.text_field :name

  = f.submit "Submit", class: 'btn btn-default'

app/views/merchants/edit.html.slim
h1 Editing merchant

== render 'form'

=> link_to 'Show', @merchant
'|
=< link_to 'Back', merchants_path

app/views/merchants/index.html.slim
h3 Listing merchants

table.table.table-striped
  thead.thead-default
    tr
      th Name
      th Products
      th

  tbody
    - @merchants.each do |merchant|
      tr
        td = merchant.name
        td = link_to 'Products', products_path(merchant_id: merchant.id)
        td
          = link_to 'Edit', edit_merchant_path(merchant), class: 'btn btn-primary'
          = link_to 'Destroy', merchant, class: 'btn btn-danger', data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Merchant', new_merchant_path, class: 'btn btn-default'

app/views/merchants/new.html.slim
h1 New merchant

== render 'form'

= link_to 'Back', merchants_path

app/views/merchants/show.html.slim
p#notice = notice

p
  strong Name:
  = @merchant.name

=> link_to 'Edit', edit_merchant_path(@merchant)
'|
=< link_to 'Back', merchants_path