config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :merchants
  resources :landlords
  resources :shops
  resources :products

  get 'qr_codes/forward/:code', to: 'qr_codes#forward', as: :forward

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end

  post "/graphql", to: "graphql#execute"
end

app/models/landlord.rb
# == Schema Information
#
# Table name: landlords
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Landlord < ApplicationRecord
  has_many :shops, dependent: :destroy
  has_many :qr_codes, dependent: :destroy

  validates :name, presence: true
end

app/controllers/landlords_controller.rb
class LandlordsController < ApplicationController
  before_action :set_landlord, only: [:show, :edit, :update, :destroy]

  # GET /landlords
  # GET /landlords.json
  def index
    @landlords = Landlord.all
  end

  # GET /landlords/1
  # GET /landlords/1.json
  def show
  end

  # GET /landlords/new
  def new
    @landlord = Landlord.new
  end

  # GET /landlords/1/edit
  def edit
  end

  # POST /landlords
  # POST /landlords.json
  def create
    @landlord = Landlord.new(landlord_params)

    respond_to do |format|
      if @landlord.save
        format.html { redirect_to @landlord, notice: 'Landlord was successfully created.' }
        format.json { render :show, status: :created, location: @landlord }
      else
        format.html { render :new }
        format.json { render json: @landlord.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /landlords/1
  # PATCH/PUT /landlords/1.json
  def update
    respond_to do |format|
      if @landlord.update(landlord_params)
        format.html { redirect_to @landlord, notice: 'Landlord was successfully updated.' }
        format.json { render :show, status: :ok, location: @landlord }
      else
        format.html { render :edit }
        format.json { render json: @landlord.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /landlords/1
  # DELETE /landlords/1.json
  def destroy
    @landlord.destroy
    respond_to do |format|
      format.html { redirect_to landlords_url, notice: 'Landlord was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_landlord
      @landlord = Landlord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def landlord_params
      params.require(:landlord).permit(:name)
    end
end

app/helpers/landlords_helper.rb
module LandlordsHelper
end

app/views/landlords/_form.html.slim
= bootstrap_form_for @landlord do |f|
  = f.text_field :name

  = f.submit "Submit", class: 'btn btn-default'

app/views/landlords/edit.html.slim
h1 Editing landlord

== render 'form'

=> link_to 'Show', @landlord
'|
=< link_to 'Back', landlords_path

app/views/landlords/index.html.slim
h3 Listing landlords

table.table.table-striped
  thead.thead-default
    tr
      th Name
      th Shops
      th

  tbody
    - @landlords.each do |landlord|
      tr
        td = landlord.name
        td = link_to 'shops', shops_path(landlord_id: landlord.id)
        td
          = link_to 'Edit', edit_landlord_path(landlord), class: 'btn btn-primary'
          = link_to 'Destroy', landlord, class: 'btn btn-danger', data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Landlord', new_landlord_path, class: 'btn btn-default'

app/views/landlords/new.html.slim
h1 New landlord

== render 'form'

= link_to 'Back', landlords_path

app/views/landlords/show.html.slim
p#notice = notice

p
  strong Name:
  = @landlord.name

=> link_to 'Edit', edit_landlord_path(@landlord)
'|
=< link_to 'Back', landlords_path