config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :merchants
  resources :landlords
  resources :shops
  resources :products

  get 'qr_codes/forward/:code', to: 'qr_codes#forward', as: :forward

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end

  post "/graphql", to: "graphql#execute"
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  name        :string
#  merchant_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Product < ApplicationRecord
  belongs_to :merchant
  has_many :qr_codes, dependent: :destroy

  validates :name, presence: true
  validates :merchant, presence: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    @products = @products.where(merchant_id: params[:merchant_id]) if params[:merchant_id].present?
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    @merchants = Merchant.all.pluck(:name, :id)
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @merchants = Merchant.all.pluck(:name, :id)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :merchant_id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.slim
= bootstrap_form_for @product do |f|
  = f.text_field :name
  = f.select :merchant_id, @merchants

  = f.submit "Submit", class: 'btn btn-default'

app/views/products/edit.html.slim
h1 Editing product

== render 'form'

=> link_to 'Show', @product
'|
=< link_to 'Back', products_path

app/views/products/index.html.slim
h3 Listing products

table.table.table-striped
  thead.thead-default
    tr
      th Name
      th Merchant
      th

  tbody
    - @products.each do |product|
      tr
        td = product.name
        td = link_to product.merchant.name, merchant_path(product.merchant)
        td
          = link_to 'Edit', edit_product_path(product), class: 'btn btn-primary'
          = link_to 'Destroy', product, class: 'btn btn-danger', data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Merchant', new_product_path, class: 'btn btn-default'

app/views/products/new.html.slim
h1 New product

== render 'form'

= link_to 'Back', products_path

app/views/products/show.html.slim
p#notice = notice

p
  strong Name:
  = @product.name
p
  strong Merchant:
  = @product.merchant

=> link_to 'Edit', edit_product_path(@product)
'|
=< link_to 'Back', products_path